version: "3.8"

services:
  frontend: # um conteiner
    depends_on: 
      - backend
    build: ./frontend
    ports:
      - 3000:3000


  backend: # outro conteiner
    depends_on: 
      - db
    build: ./backend
    ports: 
      - 3001:3001
    environment: 
      DB_URL: mongodb://db/vidly
    command: ./docker-entrypoint.sh

  db: # mais um conteiner
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db

volumes:
  vidly: